### ISSUE TITLE
Entering a wrong username/password returns Internal Server Error

### ISSUE THREAD

**Issue by alanyjw** [nushackers/printmonitor#1]
This issue occurs when the user wishes to view the printer queue. When an incorrect username/password is entered, the user is redirected to an Internal Server Error page, which prevents him/her from re-entering his/her login details. This error persists unless the user clears his/her cookies.

The website should handle such errors and prompt the user for the correct login credentials.

**Comment by muhammadhirman** [comment]
Hi yeojw
Thanks for the bug report!

Hey Gerald
Perhaps you'd like to look into this as you did the login part.

Interesting coincidence that you both have the same surname!

Muhammad Hirman

2011/9/5 yeojw reply@reply.github.com:

**Comment by alanyjw** [comment]
to be honest, i don't mind fixing it :p

but it seems like gerald hasn't uploaded the code.. :\

On Mon, Sep 5, 2011 at 3:02 PM, muhammadhirman <
reply@reply.github.com>wrote:

> Hi yeojw
> Thanks for the bug report!
> 
> Hey Gerald
> Perhaps you'd like to look into this as you did the login part.
> 
> Interesting coincidence that you both have the same surname!
> 
> Muhammad Hirman
> 
> 2011/9/5 yeojw reply@reply.github.com:
> 
> > This issue occurs when the user wishes to view the printer queue. When an
> > incorrect username/password is entered, the user is redirected to an
> > Internal Server Error page, which prevents him/her from re-entering his/her
> > login details. This error persists unless the user clears his/her cookies.
> > 
> > The website should handle such errors and prompt the user for the correct
> > login credentials.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/nushackers/printmonitor/issues/1
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nushackers/printmonitor/issues/1#issuecomment-1996258

## 

Best regards,
Alan

**Comment by muhammadhirman** [comment]
Yeah :(
I guess you'll just have to wait for Gerald to respond to this one.

Muhammad Hirman

2011/9/5 yeojw reply@reply.github.com:

> to be honest, i don't mind fixing it :p
> 
> but it seems like gerald hasn't uploaded the code.. :\
> 
> On Mon, Sep 5, 2011 at 3:02 PM, muhammadhirman <
